### ISSUE TITLE
Quarto slides with github pages

### ISSUE THREAD

**Issue by mxochicale** [mxochicale/intro-to-git-and-github#1]
Combining Quarto slides with GitHub Pages creates an excellent synergy for crafting slide templates and their structure. With this in mind, I'm kickstarting one initial iteration. For further details on quarto, have a look to this https://github.com/mxochicale/tools/tree/main/quarto

**Comment by mxochicale** [comment]
> Run quarto-dev/quarto-actions/publish@v2
Run git config --global user.email "quarto-github-actions-publish@example.com"
ERROR: Unable to publish to GitHub Pages (the remote origin does not have a branch named "gh-pages". Use first `quarto publish gh-pages` locally to initialize the remote repository for publishing.)
Stack trace:
    at resolveDeployment (file:///opt/quarto/bin/quarto.js:106225:19)
    at eventLoopTick (ext:core/01_core.js:183:[11](https://github.com/mxochicale/intro-to-git-and-github/actions/runs/8767589230/job/24061011558#step:5:12))
    at async publishAction (file:///opt/quarto/bin/quarto.js:106679:9)
    at async Command.fn (file:///opt/quarto/bin/quarto.js:106659:9)
    at async Command.execute (file:///opt/quarto/bin/quarto.js:8104:13)
    at async quarto (file:///opt/quarto/bin/quarto.js:115002:5)
    at async file:///opt/quarto/bin/quarto.js:115020:9
Error: Process completed with exit code 1.

**Comment by mxochicale** [comment]
I think I am missing  to add Github Actions `GitHub Pages Jekyll` in [settings](https://github.com/mxochicale/intro-to-git-and-github/settings/pages)  but still not sure!

**Comment by mxochicale** [comment]
:fire: published github page with slides https://mxochicale.github.io/intro-to-git-and-github/#/title-slide
